# Generated by Django 5.1.4 on 2024-12-11 11:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=100)),
                ('o_email', models.EmailField(max_length=254, unique=True)),
                ('o_password', models.CharField(max_length=250)),
                ('o_contact', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('o_website', models.CharField(max_length=100)),
                ('o_address', models.CharField(max_length=150)),
                ('o_country', models.CharField(blank=True, max_length=100, null=True)),
                ('o_state', models.CharField(blank=True, max_length=100, null=True)),
                ('o_city', models.CharField(blank=True, max_length=100, null=True)),
                ('o_pin_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_password', models.CharField(max_length=255)),
                ('e_gender', models.CharField(max_length=25)),
                ('e_contact', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=150)),
                ('e_role', models.CharField(default='Employee', max_length=150)),
                ('monitored', models.IntegerField(default=0)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='focult.organization')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_log_ts', models.DateTimeField(auto_now_add=True)),
                ('c_ip_address', models.GenericIPAddressField()),
                ('c_system_status', models.CharField(default='no', max_length=50)),
                ('c_operating_system', models.CharField(max_length=255)),
                ('c_username', models.CharField(max_length=255)),
                ('c_host_name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='focult.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='focult.organization')),
            ],
            options={
                'db_table': 'computer',
            },
        ),
    ]
